name: deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: 'NPM: Clean install and package'
      run: |
        cd slides
        npm ci
        npm run package
      env:
        CI: true
    - name: Unzip to public
      run: |
        unzip slides/rust-intro.zip -d public
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v0.1.0
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
