name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: 'NPM: Clean install and package'
      run: |
        cd slides
        npm ci
        npm run package
      env:
        CI: true
    - name: Unzip to public
      run: |
        unzip slides/rust-intro.zip -d public
    - name: Deploy to GitHub Pages
      if: success()
      uses: docker://peaceiris/gh-pages:v2.5.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
        
